# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Romesh Dhananjaya
email: romesh.d.sg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer who is currently working at Discovery Netwoks.
  I am a Sri Lankan and currently lives in Singapore.
  Graduated from University of Colombo School of Computing. I am passionate about software engineering and majour skill is java.
  Also familier with javascript.
#baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://wildflame.me' # the base hostname & protocol for your site
twitter_username: Taffyer
github_username: wild-flame

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
